### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by IngwiePhoenix** [cappuccino/objjc#1]
Hello! :)

I just remembered this project and wanted to poke around with it and Cappuccino again and the first thing I wanted to do was to install the compiler. But the package name `cappuccino.compiler` does not seem to exist on NPM, unfortunately.

Are you planning to release it to NPM at any time? And in fact, what's the status on ObjJ in Node?

Kind regards,
Ingwie.

**Comment by mrcarlberg** [comment]
Please check:
1. https://www.npmjs.com/package/objj-runtime
2. https://www.npmjs.com/package/objj-compiler

**Comment by IngwiePhoenix** [comment]
Wow, considering that Cappuchino released to 1.0.0 in september of last year, those packages seem quite outdated. And it...kinda works? Not having the frameworks included is a little bit weird, but I guess it can't be helped.

Thanks for the links! :)

**Comment by mrcarlberg** [comment]
Sorry but I gave you the wrong link to the compiler. It should be https://www.npmjs.com/package/objj-transpiler.

**Comment by mrcarlberg** [comment]
And as Cappuccino 1.0.0 has been released there are not much changes to the compiler so it should be pretty much up to date.

**Comment by IngwiePhoenix** [comment]
I think I am doing something wrong...

```
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ cat test.j
@implementation Speaker : CPObject {}
+(id) speak {
  console.log("Hello!");
}
@end

[Speaker speak];
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ objjc --ecma5 -o ./a.js ./test.j
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ cat a.js
undefined⏎                                                                                                                                                                                                 
Ingwie@Ingwies-MBP.fritz.box ~/W/T/objj $ readlink (which objjc)
../lib/node_modules/objj-transpiler/bin/objjc
```

Also good to know! Thanks for the info :)

**Comment by IngwiePhoenix** [comment]
Found it. Had to `@class CPObject;` first - but was also able to remove that alltogether and use no suberclass, and that worked just fine.

Error-handling seems to be incomplete here :)

**Comment by mrcarlberg** [comment]
As you are playing around with only the compiler you will not be able to import any other source files. So you will not be able to inherit your class from CPObject as it is not declared even if you tried to import "CPObject.j"

Try to make a class without a superclass.

**Comment by IngwiePhoenix** [comment]
I did and that effectively worked - well, it compiled.

```js
// $ objjc ./test.j --ecma5 -o test.js
{var the_class = objj_allocateClassPair(Nil, "Speaker"),
meta_class = the_class.isa;objj_registerClassPair(the_class);
class_addMethods(meta_class, [new objj_method(sel_getUid("speak"), function $Speaker__speak(self, _cmd)
{
    console.log("Hello!");
}

,["id"])]);
}
(Speaker.isa.method_msgSend["speak"] || _objj_forward)(Speaker, "speak");
```

Obviously, `Speaker` is not defined and therefore Node throws an error. The original sample is this:

```objective-j
@implementation Speaker {}
+(id) speak {
  console.log("Hello!");
}
@end

[Speaker speak];
```
