### ISSUE TITLE
Requiring the objj runtime fails

### ISSUE THREAD

**Issue by IngwiePhoenix** [cappuccino/objjc#2]
```
> var objj=require("objj-runtime/lib/objective-j")
Thrown:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.normalize (path.js:1112:5)
    at exports.normal (/Users/Ingwie/Work/Triage/objj/node_modules/common-node/lib/fs-base.js:335:32)
    at exports.relative (/Users/Ingwie/Work/Triage/objj/node_modules/common-node/lib/fs-base.js:420:44)
    at resolve (/Users/Ingwie/Work/Triage/objj/node_modules/common-node/lib/fs-base.js:347:14)
    at Object.exports.resolve (/Users/Ingwie/Work/Triage/objj/node_modules/common-node/lib/fs-base.js:375:9)
    at /Users/Ingwie/Work/Triage/objj/node_modules/objj-runtime/lib/objective-j.js:13:49
    at /Users/Ingwie/Work/Triage/objj/node_modules/objj-runtime/lib/objective-j.js:4:16
```

I do have a rough guess of what is actually happening here, because the `objj` "binary" seems to not encounter this issue - aside from the REPL immediately exiting when touching a single key. Looking at the invocation:

```js
require("../lib/objective-j").run(system.args);
```

I am honestly surprised about this. `system` should not be defined at this point: what you actually would want here is `process.argv`, or a `.slice` from it, at least. However, the file seems to be loaded anyway, so I suppose during the module's initialization, that `process.argv` is actually being processed properly, in the end.

So this leaves me a bit confused about what is actually going on. I havent inspected the source itself yet - but I definitively should :) When I find something of value here, I will post it. Three years is a lot of time, and quite some changes were made to Node over that time. So if I spot something, I will let you know!

**Comment by mrcarlberg** [comment]
This project (cappuccino/objjc) is abandon and not actively developed any more. Please don't use it.

Please use this project [objj-runtime](https://www.npmjs.com/package/objj-runtime). Read the README file for instructions.

If you want an other example please look at this [Backend](https://github.com/mrcarlberg/objj-backend) project. Read the README file for instructions how to install it.

**Comment by IngwiePhoenix** [comment]
Oops, looks like I opened this issue on the wrong repository as I was in fact using `ojj-runtime`! Sorry for that :)
